package com.clavaris.webhook.application.usecase.getwebhookdeliveryactivityfororganization;

@FunctionalInterface
public interface GetWebhookDeliveryActivityForOrganizationUseCase {

  WebhookDeliveryActivity handle(GetWebhookDeliveryActivityForOrganizationQuery query);
}
